# Server Port Configuration
server.port=${PORT:5000}

# Spring Application Name
spring.application.name=MediSphere-Backend

# Twilio Credentials Configuration
twilio.accountSid=${VITE_TWILIO_ACCOUNT_SID:${TWILIO_ACCOUNT_SID:}}
twilio.authToken=${VITE_TWILIO_AUTH_TOKEN:${TWILIO_AUTH_TOKEN:}}
twilio.phoneNumber=${VITE_TWILIO_PHONE_NUMBER:${TWILIO_PHONE_NUMBER:+18167506748}}

# Logging Configuration
logging.level.com.medisphere=DEBUG
logging.level.org.springframework.web=INFO

# Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://${PGHOST:dpg-dar36uvavr4c73fjgms0-a}:${PGPORT:5432}/${PGDATABASE:medisphere_db_2n7q}
spring.datasource.username=${PGUSER:medisphere_db_2n7q_user}
spring.datasource.password=${PGPASSWORD:uKjfNWDzybRwAnLkOebFryivpvLlVxsg}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
